name: Update README ⭐ 2022
on:
  schedule:
    - cron: "30 3/4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1.0.3
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          leaderboardId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2022
          tableMarker: '<!--- advent_readme_stars_2022 table --->'
          headerPrefix: '###'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars of year 2022